<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aid_bringup</name>
  <version>0.1.0</version>
  <description>Combined Raspberry Pi launch for AID camera and RF detection nodes.</description>
  <maintainer email="info@teknologisk.dk">Danish Technological Institute</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>aid_camera_server</exec_depend>
  <exec_depend>aid_system</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>